### ISSUE TITLE
Problème avec wireguard et l’anti ddos d’OVH

### ISSUE THREAD

**Issue by MisterGranti67** [MichelBaie/Tutos#3]
Bonjour, j'ai un problème, j'ai un tunnel via mon serveur domestique et un vps ovh sous Wireguard , tout fonctionne parfaitement, mais le problème vient du moment où je ddos ​​le vps sur le port redirigé, l'antiddos fonctionne et migre, mais bloque tout nouvel utilisateur voulant pour se connecter aux ip/ports transférés car l'anti ddos ​​pense que wireguard envoie de mauvais packet, donc wireguard déclenche la migration lorsqu'il y a une attaque ddos, donc je ne sais pas si quelqu'un a eu ce problème et si quelqu'un a réussi à le corriger mais j'aimerais avoir de l'aide merci beaucoup

**Comment by MichelBaie** [comment]
Bonjour !
L'anti-ddos d'OVH n'est pas parfait, mais ce port ne devrait pas être public et donc attaqué.
Sinon, l'IP du VPS qui est la Gateway doit rester privée car c'est notre coeur de réseau.

Si vous avez d'autres idées ou potentielles solutions, je suis ouvert.
